//
//  BackwardTexts.swift
//  Train2Read
//
//  Created by Aldiyar on 26.07.2018.
//  Copyright © 2018 Aldiyar. All rights reserved.
//

import Foundation
import UIKit
enum BackWard{
    static let citizenNormalText = "How much difference could an individual bureaucrat really make in our system? That was a popular topic for our drinking bouts. For the epic bouts, we seemed to require a Topic. The accepted wisdom, which tempered our cynicism enough to smooth the way for our complacency, was that with clever and persistent and assiduous work and some luck, the great creeping hulk that was our society could be nudged in this or that direction. But one had to be patient, and work within the system, and respect the system’s sheer size.Because, you see, our schools directed all their efforts to inculcating industriousness (somewhat successfully), obedience (fairly successfully), and toadyism (very successfully). Each graduation produced a new crop of little yes-people. Our children learned criticism from their families, and from the street."
    static let citizenText = "woH hcum ecnereffid dluoc na laudividni tarcuaerub yllaer ekam ni ruo metsys? tahT saw a ralupop cipot rof ruo gniknird stuob. roF eht cipe stuob, ew demees ot eriuqer a cipoT. ehT detpecca modsiw, hcihw derepmet ruo msicinyc hguone ot htooms eht yaw rof ruo ycnecalpmoc, saw taht htiw revelc dna tnetsisrep dna suoudissa krow dna emos kcul, eht taerg gnipeerc kluh taht saw ruo yteicos dluoc eb degdun ni siht ro taht noitcerid. tuB eno dah ot eb tneitap, dna krow nihtiw eht metsys, dna tcepser eht s’metsys reehs ezis. esuaceB, uoy ees, ruo sloohcs detcerid lla rieht stroffe ot gnitaclucni ssensuoirtsudni tahwemos( )yllufsseccus, ecneidebo ylriaf( )yllufsseccus, dna msiydaot yrev( )yllufsseccus. hcaE noitaudarg decudorp a wen porc fo elttil elpoep-sey. ruO nerdlihc denrael msicitirc morf rieht seilimaf, dna morf eht teerts. "
    static let lostJobNormalText = "Petya said the explosions made the ground shake and the water surface ripple in all directions. Pieces of concrete and steel started landing in the pond around them. They could hear the hissing as the pieces cooled. For a while they watched the cloud billow out and grow above the reactor. By then the fire was above the edge of the building. Through a crack in one of the containment walls they could see a dark blue light. “Some rich asshole’s just lost his job,” he remembered remarking to his friend. I assume he meant someone other than his eldest brother.And by then they’d both begun to feel dreadful. Their eyes streamed tears as they reeled about, so sluggish and disoriented it took them an hour to traverse the half-kilometer to the medical station. By the time they arrived, it resembled a war zone."
    static let lostJobText = "ayteP dias eht snoisolpxe edam eht dnuorg ekahs dna eht retaw ecafrus elppir ni lla snoitcerid. seceiP fo etercnoc dna leets detrats gnidnal ni eht dnop dnuora meht. yehT dluoc raeh eht gnissih sa eht seceip delooc. roF a elihw yeht dehctaw eht duolc wollib tuo dna worg evoba eht rotcaer. yB neht eht erif saw evoba eht egde fo eht gnidliub. hguorhT a kcarc ni eno fo eht tnemniatnoc sllaw yeht dluoc ees a krad eulb thgil. emoS“ hcir s’elohssa tsuj tsol sih boj,” eh derebmemer gnikramer ot sih dneirf. I emussa eh tnaem enoemos rehto naht sih tsedle rehtorb.dnA yb neht d’yeht htob nugeb ot leef lufdaerd. riehT seye demaerts sraet sa yeht deleer tuoba, os hsigguls dna detneirosid ti koot meht na ruoh ot esrevart eht retemolik-flah ot eht lacidem noitats. yB eht emit yeht devirra, ti delbmeser a raw enoz. "
    static let whatHappenedNormalText = "WHAT HAPPENED was that my older brother, Siju, got a job as a lorry driver at the mine and started acting like a big shot. He stopped playing with Munna the way he used to, tossing him into the air like a sack of sand, making him sputter with laughter. When Amma asked him anything, he would give her a pitying look and not answer. He stopped speaking to his girlfriend, Manju, altogether. He taunted me about playing in the mud, as he called it, breaking chunks of iron ore with my hammer. With Appa especially he was reckless, not bothering to conceal his disdain, until he said something about failed drivers who are only good for digging and drinking, and Appa wrestled him to the ground and forced him to eat a handful of the red, iron-rich earth, shouting that this was our living now and he should bloody learn to respect it. Siju complained to the mine’s labor officer, Mr. Subbu, but Mr. Subbu dismissed it as a domestic matter and refused to interfere. After that, Siju maintained a glowering silence in Appa’s presence. When Appa wasn’t around, Siju sneered at our tent, a swatch of blue plastic stretched over a bamboo skeleton. Never mind that he was being paid half a regular driver’s salary by the owner of the lorry, a paan-chewing Andhra fellow called Rajappa, because Siju was only fourteen and could not bargain for more."
    static let whatHappenedText = "TAHW DENEPPAH saw taht ym redlo rehtorb, ujiS, tog a boj sa a yrrol revird ta eht enim dna detrats gnitca ekil a gib tohs. eH deppots gniyalp htiw annuM eht yaw eh desu ot, gnissot mih otni eht ria ekil a kcas fo dnas, gnikam mih rettups htiw rethgual. nehW ammA deksa mih gnihtyna, eh dluow evig reh a gniytip kool dna ton rewsna. eH deppots gnikaeps ot sih dneirflrig, ujnaM, rehtegotla. eH detnuat em tuoba gniyalp ni eht dum, sa eh dellac ti, gnikaerb sknuhc fo nori ero htiw ym remmah. htiW appA yllaicepse eh saw sselkcer, ton gnirehtob ot laecnoc sih niadsid, litnu eh dias gnihtemos tuoba deliaf srevird ohw era ylno doog rof gniggid dna gniknird, dna appA deltserw mih ot eht dnuorg dna decrof mih ot tae a lufdnah fo eht der, hcir-nori htrae, gnituohs taht siht saw ruo gnivil won dna eh dluohs ydoolb nrael ot tcepser ti. ujiS denialpmoc ot eht s’enim robal reciffo, rM. ubbuS, tub rM. ubbuS dessimsid ti sa a citsemod rettam dna desufer ot erefretni. retfA taht, ujiS deniatniam a gnirewolg ecnelis ni s’appA ecneserp. nehW appA t’nsaw dnuora, ujiS dereens ta ruo tnet, a hctaws fo eulb citsalp dehcterts revo a oobmab noteleks. reveN dnim taht eh saw gnieb diap flah a raluger s’revird yralas yb eht renwo fo eht yrrol, a gniwehc-naap arhdnA wollef dellac appajaR, esuaceb ujiS saw ylno neetruof dna dluoc ton niagrab rof erom. "
    static let paybackNormalText = "Stabler and Benson investigate the murder and castration of a New York City cab driver. They discover that the victim assumed the identity of another man years before because he was wanted by police. In the end, Stabler discovers that the stolen identity of the man in question was also stolen, and he and Benson have to begin the investigation all over again. That night, as he unsuccessfully tries to sleep, Stabler begins to hear a strange noise. A deep drumming, two beats. It seems like it’s coming from his basement. When he investigates the basement, it sounds like it’s coming from outside."
    static let paybackText = "kcabyaP.relbatS dna nosneB etagitsevni eht redrum dna noitartsac fo a weN kroY ytiC bac revird. yehT revocsid taht eht mitciv demussa eht ytitnedi fo rehtona nam sraey erofeb esuaceb eh saw detnaw yb ecilop. nI eht dne, relbatS srevocsid taht eht nelots ytitnedi fo eht nam ni noitseuq saw osla nelots, dna eh dna nosneB evah ot nigeb eht noitagitsevni lla revo niaga. tahT thgin, sa eh yllufsseccusnu seirt ot peels, relbatS snigeb ot raeh a egnarts esion. A peed gnimmurd, owt staeb. tI smees ekil s’ti gnimoc morf sih tnemesab. nehW eh setagitsevni eht tnemesab, ti sdnuos ekil s’ti gnimoc morf edistuo. "
}
